/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.hanabi1224.RuAnnoy

import java.util.Arrays
import kotlin.test.*

class AnnoyIndexTest {
        @Test
        fun testAnnoyIndex() {
                if (!System.getenv("JITPACK").isNullOrBlank()) {
                        return
                }

                val indexPath = "$pwd/src/test/resources/index.angular.5d.ann"
                val index = AnnoyIndex.tryLoad(indexPath, 5, IndexType.Angular)
       