/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.hanabi1224.RuAnnoy

import java.util.Arrays
import kotlin.test.*

class AnnoyIndexTest {
        @Test
        fun testAnnoyIndex() {
                if (!System.getenv("JITPACK").isNullOrBlank()) {
                        return
                }

                val indexPath = "$pwd/src/test/resources/index.angular.5d.ann"
                val index = AnnoyIndex.tryLoad(indexPath, 5, IndexType.Angular)
                assertTrue(index != null, "indexPath: $indexPath")
                assertEquals(100, index.size)
                index.use {
                        assertEquals(5, index.dimension)
                        val v3 = index.getItemVector(3)
                        assertTrue(
                                        v3.toTypedArray()
                                                        .contentDeepEquals(
                                                                        floatArrayOf(
                                                                                                        -0.38846132159233093f,
                                                                                                        0.8791206479